[project]
name = "python-serial-recorder"
version = "0.1.0"
description = "Python Serial Recorder"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "darkdetect",
    "matplotlib",
    "openpyxl",
    "pandas",
    "pyserial",
    "pyside6",
]


[tools.uv]
link-mode = "copy"